delimiter $$

CREATE TABLE `artists` (
  `artist_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT 'f_key',
  `type` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `genre` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `no_of_members` smallint(6) DEFAULT NULL,
  `bio` text COLLATE utf8_unicode_ci NOT NULL,
  `rating` double DEFAULT NULL,
  `verified` tinyint(1) NOT NULL DEFAULT '0',
  `gig_count` int(11) NOT NULL DEFAULT '0',
  `profile_picture` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`artist_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `artists_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Table with specific artist details'$$


delimiter $$

CREATE TABLE `comments` (
  `comment_id` int(11) NOT NULL AUTO_INCREMENT,
  `post_id` int(11) NOT NULL,
  `created` timestamp NULL DEFAULT NULL,
  `modified` timestamp NULL DEFAULT NULL,
  `author_id` int(11) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`comment_id`),
  KEY `fk_postid` (`post_id`),
  KEY `fk_userid` (`author_id`),
  CONSTRAINT `fk_postid` FOREIGN KEY (`post_id`) REFERENCES `posts` (`post_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_userid` FOREIGN KEY (`author_id`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1 COMMENT='comments in posts'$$


delimiter $$

CREATE TABLE `connections` (
  `connection_id` int(11) NOT NULL AUTO_INCREMENT,
  `from_id` int(11) NOT NULL,
  `to_id` int(11) NOT NULL,
  `status` int(11) DEFAULT '0',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`connection_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1 COMMENT='stores the connections'$$


delimiter $$

CREATE TABLE `contacts` (
  `contact_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `surname` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `city` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `address_1` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `address_2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'optional',
  `email_1` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'different from user email',
  `email_2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'optional, different from user email',
  `postcode` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `phone_1` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `phone_2` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'optional',
  `user_id` int(11) NOT NULL COMMENT 'f_key',
  PRIMARY KEY (`contact_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `contacts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='general contact details'$$


delimiter $$

CREATE TABLE `geocodes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(100) NOT NULL,
  `lng` float(10,6) NOT NULL,
  `lat` float(10,6) NOT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `address3` varchar(255) DEFAULT NULL,
  `address4` varchar(255) DEFAULT NULL,
  `town` varchar(90) DEFAULT NULL,
  `postcode` varchar(10) DEFAULT NULL,
  `country` varchar(6) DEFAULT NULL,
  `provider` varchar(30) DEFAULT NULL,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created` datetime NOT NULL,
  `user_id` int(11) NOT NULL,
  `type` varchar(45) NOT NULL COMMENT 'the account type (venue or artist)',
  PRIMARY KEY (`id`),
  KEY `fkuserid1` (`user_id`),
  CONSTRAINT `fkuserid1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1$$


delimiter $$

CREATE TABLE `gig_ads` (
  `gig_ad_id` int(11) NOT NULL AUTO_INCREMENT,
  `venue_user_id` int(11) NOT NULL,
  `looking_type` varchar(45) NOT NULL,
  `looking_genre` varchar(45) NOT NULL,
  `looking_date` datetime NOT NULL,
  `looking_moreinfo` text COMMENT 'some more information about the ad',
  `created` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`gig_ad_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$


delimiter $$

CREATE TABLE `gig_requests` (
  `gig_request_id` int(11) NOT NULL AUTO_INCREMENT,
  `from_artist_id` varchar(45) NOT NULL,
  `to_venue_id` varchar(45) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `gig_ad_id` int(11) DEFAULT NULL COMMENT 'If the request referes to a gig ad_id',
  `message` longtext NOT NULL,
  PRIMARY KEY (`gig_request_id`),
  KEY `fk_gigadid` (`gig_ad_id`),
  CONSTRAINT `fk_gigadid` FOREIGN KEY (`gig_ad_id`) REFERENCES `gig_ads` (`gig_ad_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$


delimiter $$

CREATE TABLE `gigs` (
  `gig_id` int(11) NOT NULL AUTO_INCREMENT,
  `status` varchar(45) NOT NULL COMMENT 'upcoming,ongoing,\nended',
  `artist_name` varchar(45) NOT NULL,
  `artist_user_id` int(11) NOT NULL,
  `venue_name` varchar(45) NOT NULL,
  `venue_user_id` int(11) NOT NULL,
  `gig_picture` varchar(100) NOT NULL,
  `about` longtext NOT NULL,
  `date_time` datetime NOT NULL,
  `rating` double DEFAULT NULL,
  PRIMARY KEY (`gig_id`),
  KEY `fk_gigs_1` (`artist_user_id`),
  KEY `fk_gigs_2` (`venue_user_id`),
  CONSTRAINT `fk_gigs_1` FOREIGN KEY (`artist_user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_gigs_2` FOREIGN KEY (`venue_user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$


delimiter $$

CREATE TABLE `posts` (
  `post_id` int(11) NOT NULL AUTO_INCREMENT,
  `from_id` int(11) NOT NULL,
  `to_id` int(11) NOT NULL,
  `text` longtext NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `from_type` varchar(10) NOT NULL,
  PRIMARY KEY (`post_id`)
) ENGINE=InnoDB AUTO_INCREMENT=99 DEFAULT CHARSET=latin1 COMMENT='table that stores the posts'$$


delimiter $$

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `account_type` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT '''venue'' or ''artist''',
  `join_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Basic user information'$$


delimiter $$

CREATE TABLE `venues` (
  `venue_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT 'f_key',
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'pub,club,e.t.c',
  `location` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `capacity` int(11) NOT NULL,
  `opening_times` text COLLATE utf8_unicode_ci,
  `rating` double DEFAULT '0',
  `profile_picture` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`venue_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `venues_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci$$


INSERT INTO `gag_db`.`artists`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>
);


INSERT INTO `gag_db`.`comments`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>
);


INSERT INTO `gag_db`.`connections`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>
);


INSERT INTO `gag_db`.`contacts`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>
);


INSERT INTO `gag_db`.`geocodes`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>
);


INSERT INTO `gag_db`.`gig_ads`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`,
`gig_ad_id`,
`venue_user_id`,
`looking_type`,
`looking_genre`,
`looking_date`,
`looking_moreinfo`,
`created`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>,
<{gig_ad_id: }>,
<{venue_user_id: }>,
<{looking_type: }>,
<{looking_genre: }>,
<{looking_date: }>,
<{looking_moreinfo: }>,
<{created: }>
);


INSERT INTO `gag_db`.`gig_requests`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`,
`gig_ad_id`,
`venue_user_id`,
`looking_type`,
`looking_genre`,
`looking_date`,
`looking_moreinfo`,
`created`,
`gig_request_id`,
`from_artist_id`,
`to_venue_id`,
`created`,
`gig_ad_id`,
`message`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>,
<{gig_ad_id: }>,
<{venue_user_id: }>,
<{looking_type: }>,
<{looking_genre: }>,
<{looking_date: }>,
<{looking_moreinfo: }>,
<{created: }>,
<{gig_request_id: }>,
<{from_artist_id: }>,
<{to_venue_id: }>,
<{created: CURRENT_TIMESTAMP}>,
<{gig_ad_id: }>,
<{message: }>
);


INSERT INTO `gag_db`.`gigs`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`,
`gig_ad_id`,
`venue_user_id`,
`looking_type`,
`looking_genre`,
`looking_date`,
`looking_moreinfo`,
`created`,
`gig_request_id`,
`from_artist_id`,
`to_venue_id`,
`created`,
`gig_ad_id`,
`message`,
`gig_id`,
`status`,
`artist_name`,
`artist_user_id`,
`venue_name`,
`venue_user_id`,
`gig_picture`,
`about`,
`date_time`,
`rating`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>,
<{gig_ad_id: }>,
<{venue_user_id: }>,
<{looking_type: }>,
<{looking_genre: }>,
<{looking_date: }>,
<{looking_moreinfo: }>,
<{created: }>,
<{gig_request_id: }>,
<{from_artist_id: }>,
<{to_venue_id: }>,
<{created: CURRENT_TIMESTAMP}>,
<{gig_ad_id: }>,
<{message: }>,
<{gig_id: }>,
<{status: }>,
<{artist_name: }>,
<{artist_user_id: }>,
<{venue_name: }>,
<{venue_user_id: }>,
<{gig_picture: }>,
<{about: }>,
<{date_time: }>,
<{rating: }>
);


INSERT INTO `gag_db`.`posts`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`,
`gig_ad_id`,
`venue_user_id`,
`looking_type`,
`looking_genre`,
`looking_date`,
`looking_moreinfo`,
`created`,
`gig_request_id`,
`from_artist_id`,
`to_venue_id`,
`created`,
`gig_ad_id`,
`message`,
`gig_id`,
`status`,
`artist_name`,
`artist_user_id`,
`venue_name`,
`venue_user_id`,
`gig_picture`,
`about`,
`date_time`,
`rating`,
`post_id`,
`from_id`,
`to_id`,
`text`,
`date`,
`from_type`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>,
<{gig_ad_id: }>,
<{venue_user_id: }>,
<{looking_type: }>,
<{looking_genre: }>,
<{looking_date: }>,
<{looking_moreinfo: }>,
<{created: }>,
<{gig_request_id: }>,
<{from_artist_id: }>,
<{to_venue_id: }>,
<{created: CURRENT_TIMESTAMP}>,
<{gig_ad_id: }>,
<{message: }>,
<{gig_id: }>,
<{status: }>,
<{artist_name: }>,
<{artist_user_id: }>,
<{venue_name: }>,
<{venue_user_id: }>,
<{gig_picture: }>,
<{about: }>,
<{date_time: }>,
<{rating: }>,
<{post_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{text: LONGTEXT}>,
<{date: TIMESTAMP}>,
<{from_type: VARCHAR}>
);


INSERT INTO `gag_db`.`users`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`,
`gig_ad_id`,
`venue_user_id`,
`looking_type`,
`looking_genre`,
`looking_date`,
`looking_moreinfo`,
`created`,
`gig_request_id`,
`from_artist_id`,
`to_venue_id`,
`created`,
`gig_ad_id`,
`message`,
`gig_id`,
`status`,
`artist_name`,
`artist_user_id`,
`venue_name`,
`venue_user_id`,
`gig_picture`,
`about`,
`date_time`,
`rating`,
`post_id`,
`from_id`,
`to_id`,
`text`,
`date`,
`from_type`,
`user_id`,
`username`,
`password`,
`email`,
`account_type`,
`join_date`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>,
<{gig_ad_id: }>,
<{venue_user_id: }>,
<{looking_type: }>,
<{looking_genre: }>,
<{looking_date: }>,
<{looking_moreinfo: }>,
<{created: }>,
<{gig_request_id: }>,
<{from_artist_id: }>,
<{to_venue_id: }>,
<{created: CURRENT_TIMESTAMP}>,
<{gig_ad_id: }>,
<{message: }>,
<{gig_id: }>,
<{status: }>,
<{artist_name: }>,
<{artist_user_id: }>,
<{venue_name: }>,
<{venue_user_id: }>,
<{gig_picture: }>,
<{about: }>,
<{date_time: }>,
<{rating: }>,
<{post_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{text: LONGTEXT}>,
<{date: TIMESTAMP}>,
<{from_type: VARCHAR}>,
<{user_id: INT}>,
<{username: VARCHAR}>,
<{password: VARCHAR}>,
<{email: VARCHAR}>,
<{account_type: VARCHAR}>,
<{join_date: TIMESTAMP}>
);


INSERT INTO `gag_db`.`venues`
(`artist_id`,
`user_id`,
`type`,
`name`,
`location`,
`genre`,
`no_of_members`,
`bio`,
`rating`,
`verified`,
`gig_count`,
`profile_picture`,
`comment_id`,
`post_id`,
`created`,
`modified`,
`author_id`,
`text`,
`connection_id`,
`from_id`,
`to_id`,
`status`,
`date`,
`contact_id`,
`name`,
`surname`,
`city`,
`address_1`,
`address_2`,
`email_1`,
`email_2`,
`postcode`,
`phone_1`,
`phone_2`,
`user_id`,
`id`,
`key`,
`lng`,
`lat`,
`address1`,
`address2`,
`address3`,
`address4`,
`town`,
`postcode`,
`country`,
`provider`,
`modified`,
`created`,
`user_id`,
`type`,
`gig_ad_id`,
`venue_user_id`,
`looking_type`,
`looking_genre`,
`looking_date`,
`looking_moreinfo`,
`created`,
`gig_request_id`,
`from_artist_id`,
`to_venue_id`,
`created`,
`gig_ad_id`,
`message`,
`gig_id`,
`status`,
`artist_name`,
`artist_user_id`,
`venue_name`,
`venue_user_id`,
`gig_picture`,
`about`,
`date_time`,
`rating`,
`post_id`,
`from_id`,
`to_id`,
`text`,
`date`,
`from_type`,
`user_id`,
`username`,
`password`,
`email`,
`account_type`,
`join_date`,
`venue_id`,
`user_id`,
`name`,
`type`,
`location`,
`capacity`,
`opening_times`,
`rating`,
`profile_picture`)
VALUES
(
<{artist_id: }>,
<{user_id: }>,
<{type: }>,
<{name: }>,
<{location: }>,
<{genre: }>,
<{no_of_members: }>,
<{bio: }>,
<{rating: }>,
<{verified: 0}>,
<{gig_count: 0}>,
<{profile_picture: }>,
<{comment_id: INT}>,
<{post_id: INT}>,
<{created: TIMESTAMP}>,
<{modified: TIMESTAMP}>,
<{author_id: INT}>,
<{text: TEXT}>,
<{connection_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{status: INT}>,
<{date: TIMESTAMP}>,
<{contact_id: INT}>,
<{name: VARCHAR}>,
<{surname: VARCHAR}>,
<{city: VARCHAR}>,
<{address_1: VARCHAR}>,
<{address_2: VARCHAR}>,
<{email_1: VARCHAR}>,
<{email_2: VARCHAR}>,
<{postcode: VARCHAR}>,
<{phone_1: VARCHAR}>,
<{phone_2: VARCHAR}>,
<{user_id: INT}>,
<{id: INT}>,
<{key: VARCHAR}>,
<{lng: FLOAT}>,
<{lat: FLOAT}>,
<{address1: VARCHAR}>,
<{address2: VARCHAR}>,
<{address3: VARCHAR}>,
<{address4: VARCHAR}>,
<{town: VARCHAR}>,
<{postcode: VARCHAR}>,
<{country: VARCHAR}>,
<{provider: VARCHAR}>,
<{modified: TIMESTAMP}>,
<{created: DATETIME}>,
<{user_id: INT}>,
<{type: VARCHAR}>,
<{gig_ad_id: }>,
<{venue_user_id: }>,
<{looking_type: }>,
<{looking_genre: }>,
<{looking_date: }>,
<{looking_moreinfo: }>,
<{created: }>,
<{gig_request_id: }>,
<{from_artist_id: }>,
<{to_venue_id: }>,
<{created: CURRENT_TIMESTAMP}>,
<{gig_ad_id: }>,
<{message: }>,
<{gig_id: }>,
<{status: }>,
<{artist_name: }>,
<{artist_user_id: }>,
<{venue_name: }>,
<{venue_user_id: }>,
<{gig_picture: }>,
<{about: }>,
<{date_time: }>,
<{rating: }>,
<{post_id: INT}>,
<{from_id: INT}>,
<{to_id: INT}>,
<{text: LONGTEXT}>,
<{date: TIMESTAMP}>,
<{from_type: VARCHAR}>,
<{user_id: INT}>,
<{username: VARCHAR}>,
<{password: VARCHAR}>,
<{email: VARCHAR}>,
<{account_type: VARCHAR}>,
<{join_date: TIMESTAMP}>,
<{venue_id: INT}>,
<{user_id: INT}>,
<{name: VARCHAR}>,
<{type: VARCHAR}>,
<{location: VARCHAR}>,
<{capacity: INT}>,
<{opening_times: TEXT}>,
<{rating: DOUBLE}>,
<{profile_picture: TEXT}>
);


